eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  zipkin.base-url: http://localhost:9411/
  
  application:
    name: USER-SERVICE
    
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/employeestore
    username: root
  
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - "*"
  tracing:
    sampling:
      probability: 1.0
        
  endpoint:
    health:
      show-details: always
      

resilience4j:
  circuitbreaker:
    instances:
      customer_fallback:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 40
        minimum-number-of-calls: 4
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based

server:
  port: 8018